### ISSUE TITLE
Describe response objects generated from "returns" by strong-remoting

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-swagger#27]
https://github.com/strongloop/loopback-swagger/blob/6d13c8c75978e88ed31c0921765f0b6959f36fdb/lib/specgen/route-helper.js#L104-L111
> Convert `returns` into a single object for later conversion into an
> operation object.
> TODO ad-hoc model definition in the case of multiple return values.
> It is enough to replace 'object' with an anonymous type definition
> based on all routeReturn items. The schema converter should take
> care of the remaning conversions.

A good example of such method is `PersistedModel.count`, as described in https://github.com/strongloop/loopback/issues/2043.

```js
  setRemoting(PersistedModel, 'count', {
      description: 'Count instances of the model matched by where from the data source.',
      accessType: 'READ',
      accepts: {arg: 'where', type: 'object', description: 'Criteria to match model instances'},
      returns: {arg: 'count', type: 'number'},
      http: {verb: 'get', path: '/count'}
    });
```

Server response:

```json
{
  "count": 123
}
```

Swagger spec we generate now:

```yaml
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
```

**Comment by bajtos** [comment]
I asked @hideya to help us to implement this feature.

Where to start: https://github.com/strongloop/loopback-swagger/blob/master/lib/specgen/route-helper.js#L104-L111

1) convert each "returns" argument into a property description
2) register a new type with the properties from 1) - you already have access to "schemaBuilder" and "typeRegistry", just call the right methods. The type name should be generated, probably using operations id, e.g. "MyModelCreateResult"
3) convertReturnsToSwagger should return a reference to the type built in 2)

And here is the test-case to modify: https://github.com/strongloop/loopback-swagger/blob/cc10105fdc7780e05bca37b9070b48aa99a7cb3a/test/specgen/route-helper.test.js#L9-L20 Please add more test cases as needed, I would personally verify at least two cases: the current case with multiple args, and then the case with a single argument, like we have in MyModel.count()

**Comment by hideya** [comment]
@bajtos as a part of looking into a fix of this issue, I did a bit further investigation of swagger-codegen's `responses: schema:` handling.  What I figured out is that, for the case of server response `{ "count": 123 }`, if Swagger spec we generate had looked like the following:
```yaml
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
          required:
          - count
          properties:
            count:
              type: number
```
`swagger-codegen` automatically generates a client-side model (class) to access this particular response object (in Obj-C case, it is named like `XXInlineResponse2002`).  Using that model, we can write code like the following to obtain the `count` value through the property:
```objc
 [coffeeShopApi coffeeShopCountWithWhere:nil completionHandler:^(XXInlineResponse2001 *output, NSError *error) {
     NSLog(@"count: %@", output.count);
 }];
```
If we don't list any `properties:` in the spec, swagger-codegen generates a model with no properties (thus, no way to access the `count` value using it).  This was what happening with the current Swagger spec we generate.

So, alternative approach to deal with this issue is that, instead of creating and registering a new type comprise of response object's properties within loopback-swagger, we add those extra information to `responses: schema:` and let swagger-codegen handle it.  I think this may be a way to go.  What would you think?

**Comment by bajtos** [comment]
> So, alternative approach to deal with this issue is that, instead of creating and registering a new type comprise of response object's properties within loopback-swagger, we add those extra information to `responses: schema:` and let swagger-codegen handle it.

Nice! I didn't realise we can specify the properties directly in response schema.

> I think this may be a way to go. What would you think?

Yes please, let's do what you are proposing.

**Comment by bajtos** [comment]
The swagger schema allows a `title` property, makes me wonder if we can leverage it to get a nicer client class name than `InlineResponse2001`? This is nice to have though.

**Comment by hideya** [comment]
I'll try out `title` property quickly.  Since it could be tricky to give clean human friendly but unique name per return object.  In that case, I'll leave the class name as it is for now.

**Comment by hideya** [comment]
@bajtos I quickly tried setting a `title` property, and found it doesn't have any effect against the generated code.  Keep working on the fix...

**Comment by bajtos** [comment]
>  I quickly tried setting a title property, and found it doesn't have any effect against the generated code. 

No problem, don't worry about the `title` then.
